remote_theme: boycce/github-docs
title: Cherry
description: Minimal and comprehensible CSS framework
github_url: "https://github.com/boycce/cherry"
port: 4001
basedir: "docs"

# Aux links for the naviation
aux_links:
  "Cherry on GitHub":
    - "//github.com/boycce/cherry"

defaults:
  -
    scope:
      path: "readme.md"
    values:
      title: "Introduction"
      nav_order: 1
